apiVersion: operator.ibm.com/v1alpha1
kind: SecurityOnboarding
metadata:
  name: example-securityonboarding
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
spec:
  # Add fields here
  operatorVersion: "0.14.1"
  replicas: 1
  securityOnboardingJob:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-iam-onboarding"
    imageTag: "3.3.3"
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 20m
        memory: 64Mi
  iamOnboarding:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-iam-onboarding"
    imageTag: "3.3.3"
    resources:
      limits:
        cpu: 200m
        memory: 1024Mi
      requests:
        cpu: 20m
        memory: 64M
  initAuthService:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-platform-auth"
    imageTag: "3.3.7"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128M
  initIdentityProvider:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-platform-auth"
    imageTag: "3.3.7"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128M
  initIdentityManager:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-platform-auth"
    imageTag: "3.3.7"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128M
  initTokenService:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-platform-auth"
    imageTag: "3.3.7"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128M
  initPAPSpec:
    imageRegistry: "quay.io/opencloudio"
    imageName: "icp-platform-auth"
    imageTag: "3.3.7"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128M
  impersonation:
    enableImpersonation: false
