apiVersion: operator.ibm.com/v1alpha1
kind: Pap
metadata:
  name: example-pap
spec:
  # Add fields here
  auditService:
    imageRegistry: "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64"
    imageName: "icp-audit-service"
    imageTag: "3.3.0"
    journalPath: "/run/systemd/journal"
  papService:
    imageRegistry: "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64"
    imageName: "iam-policy-administration"
    imageTag: "3.3.0"
  operatorVersion: "3.5.0"
  replicas: 1