apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-psql-iam
spec:
  instances: 3
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
  certificates:
    clientCASecret: iam-postgres-client-cert
    replicationTLSSecret: iam-postgres-client-cert
    serverCASecret: iam-postgres-server-cert
    serverTLSSecret: iam-postgres-server-cert
