kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-iam-operator
subjects:
- kind: ServiceAccount
  name: ibm-iam-operator
roleRef:
  kind: Role
  name: ibm-iam-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-iam-operator
subjects:
- kind: ServiceAccount
  name: ibm-iam-operator
  namespace: ibm-common-services
roleRef:
    kind: ClusterRole
    name: ibm-iam-operator
    apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-iam-operand-privileged
subjects:
- kind: ServiceAccount
  name: ibm-iam-operand-privileged
roleRef:
  kind: Role
  name: ibm-iam-operand-privileged
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-iam-operand-privileged
subjects:
- kind: ServiceAccount
  name: ibm-iam-operand-privileged
  namespace: ibm-common-services
roleRef:
    kind: ClusterRole
    name: ibm-iam-operand-privileged
    apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-iam-operand-restricted
subjects:
- kind: ServiceAccount
  name: ibm-iam-operand-restricted
roleRef:
  kind: Role
  name: ibm-iam-operand-restricted
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-iam-operand-restricted
subjects:
- kind: ServiceAccount
  name: ibm-iam-operand-restricted
  namespace: ibm-common-services
roleRef:
    kind: ClusterRole
    name: ibm-iam-operand-restricted
    apiGroup: rbac.authorization.k8s.io
