apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: authentications.operator.ibm.com
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
spec:
  group: operator.ibm.com
  names:
    kind: Authentication
    listKind: AuthenticationList
    plural: authentications
    singular: authentication
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Authentication is the Schema for the authentications API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AuthenticationSpec defines the desired state of Authentication
          properties:
            auditService:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                journalPath:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              - journalPath
              type: object
            authService:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                ldapsCACert:
                  type: string
                routerCertSecret:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              - ldapsCACert
              - routerCertSecret
              type: object
            clientRegistration:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            config:
              properties:
                authUniqueHosts:
                  type: string
                clusterCADomain:
                  type: string
                clusterExternalAddress:
                  type: string
                clusterInternalAddress:
                  type: string
                clusterName:
                  type: string
                defaultAdminPassword:
                  type: string
                defaultAdminUser:
                  type: string
                enableImpersonation:
                  type: boolean
                fipsEnabled:
                  type: boolean
                icpPort:
                  format: int32
                  type: integer
                installType:
                  type: string
                isOpenshiftEnv:
                  type: boolean
                oidcIssuerURL:
                  type: string
                openshiftPort:
                  format: int32
                  type: integer
                roksEnabled:
                  type: boolean
                nonceEnabled:
                  type: boolean
                basicUser:
                  type: string 
                roksURL:
                  type: string
                roksUserPrefix:
                  type: string
                wlpClientID:
                  type: string
                wlpClientRegistrationSecret:
                  type: string
                wlpClientSecret:
                  type: string
              required:
              - authUniqueHosts
              - clusterCADomain
              - clusterExternalAddress
              - clusterInternalAddress
              - clusterName
              - defaultAdminPassword
              - defaultAdminUser
              - enableImpersonation
              - fipsEnabled
              - icpPort
              - installType
              - isOpenshiftEnv
              - oidcIssuerURL
              - openshiftPort
              - roksEnabled
              - nonceEnabled
              - roksURL
              - roksUserPrefix
              - wlpClientID
              - wlpClientRegistrationSecret
              - wlpClientSecret
              type: object
            identityManager:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                masterNodesList:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              - masterNodesList
              type: object
            identityProvider:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            initMongodb:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            operatorVersion:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            replicas:
              format: int32
              type: integer
          required:
          - auditService
          - authService
          - clientRegistration
          - config
          - identityManager
          - identityProvider
          - initMongodb
          - operatorVersion
          - replicas
          type: object
        status:
          description: AuthenticationStatus defines the observed state of Authentication
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
