- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ICP_PLATFORM_AUTH_IMAGE
    value: icr.io/cpopen/cpfs/icp-platform-auth:4.10.0
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ICP_IDENTITY_PROVIDER_IMAGE
    value: icr.io/cpopen/cpfs/icp-identity-provider:4.10.0
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ICP_IDENTITY_MANAGER_IMAGE
    value: icr.io/cpopen/cpfs/icp-identity-manager:4.10.0
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: IM_INITCONTAINER_IMAGE
    value: icr.io/cpopen/cpfs/im-initcontainer:4.10.0
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: IfNotPresent
