apiVersion: operator.ibm.com/v1alpha1
kind: Authentication
metadata:
  name: example-authentication
spec:
  authService:
    imageRegistry: icr.io/cpopen/cpfs
    imageTag: 4.15.0
  clientRegistration:
    imageRegistry: icr.io/cpopen/cpfs
    imageTag: 4.15.0
  identityManager:
    imageRegistry: icr.io/cpopen/cpfs
    imageTag: 4.15.0
  identityProvider:
    imageRegistry: icr.io/cpopen/cpfs
    imageTag: 4.15.0
  initMongodb:
    imageRegistry: icr.io/cpopen/cpfs
    imageTag: 4.15.0
