channels:
- currentCSV: ibm-iam-operator.v3.6.0
  name: dev
- currentCSV: ibm-iam-operator.v3.6.0
  name: beta
- currentCSV: ibm-iam-operator.v3.5.0
  name: stable-v1
defaultChannel: beta
packageName: ibm-iam-operator
