channels:
- currentCSV: ibm-iam-operator.v3.7.3
  name: beta
- currentCSV: ibm-iam-operator.v3.7.4
  name: dev
- currentCSV: ibm-iam-operator.v3.7.2
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-iam-operator
