channels:
- currentCSV: ibm-iam-operator.v3.8.0
  name: beta
- currentCSV: ibm-iam-operator.v3.8.1
  name: dev
- currentCSV: ibm-iam-operator.v3.7.5
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-iam-operator
