channels:
- currentCSV: ibm-iam-operator.v3.6.2
  name: dev
- currentCSV: ibm-iam-operator.v3.6.2
  name: beta
- currentCSV: ibm-iam-operator.v3.6.2
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-iam-operator
